// @generated by console/scripts/embed-dist.mjs; do not edit by hand.

#[rustfmt::skip]
pub(crate) fn get(path: &str) -> Option<(&'static str, &'static [u8])> {
    match path {
        "app.js" => Some(("text/javascript; charset=utf-8", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/console/app.js")))),
        "assets/index-Dtv5WqkP.js" => Some(("text/javascript; charset=utf-8", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/console/assets/index-Dtv5WqkP.js")))),
        "assets/index-Dz_Oz8Yg.css" => Some(("text/css; charset=utf-8", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/console/assets/index-Dz_Oz8Yg.css")))),
        "history.js" => Some(("text/javascript; charset=utf-8", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/console/history.js")))),
        "index.html" => Some(("text/html; charset=utf-8", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/console/index.html")))),
        "manifest.json" => Some(("application/json; charset=utf-8", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/console/manifest.json")))),
        "style.css" => Some(("text/css; charset=utf-8", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/console/style.css")))),
        _ => None,
    }
}
