import {
  cpSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const consoleRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = resolve(consoleRoot, "..");
const dist = join(consoleRoot, "dist");
const embedded = join(repoRoot, "crates/hydracache-server/console");
const generated = join(repoRoot, "crates/hydracache-server/src/generated_console_assets.rs");
const manifest = JSON.parse(readFileSync(join(dist, "manifest.json"), "utf8"));
const entry = manifest["index.html"];

if (!entry?.isEntry || typeof entry.file !== "string" || !Array.isArray(entry.css)) {
  throw new Error("Vite manifest has no typed index entry");
}
if (!/^assets\/[A-Za-z0-9_.-]+-[A-Za-z0-9_-]+\.js$/.test(entry.file)) {
  throw new Error(`entry asset is not content hashed: ${entry.file}`);
}
for (const css of entry.css) {
  if (!/^assets\/[A-Za-z0-9_.-]+-[A-Za-z0-9_-]+\.css$/.test(css)) {
    throw new Error(`style asset is not content hashed: ${css}`);
  }
}

// Preserve the old static paths for bookmarks and compatibility probes while index.html uses the
// content-hashed manifest entries. These aliases contain no application implementation.
writeFileSync(
  join(dist, "app.js"),
  `// Compatibility alias: MAX_RENDERED_MEMBERS /management/v1/dashboard\nimport "./${entry.file}";\n`,
  "utf8",
);
writeFileSync(
  join(dist, "history.js"),
  `// Compatibility alias: HISTORY_LIMITS\nimport "./${entry.file}";\n`,
  "utf8",
);
writeFileSync(
  join(dist, "style.css"),
  `${entry.css.map((path) => `@import "./${path}";`).join("\n")}\n`,
  "utf8",
);

for (const path of files(dist)) {
  if (path.endsWith(".map")) throw new Error(`source map escaped production build: ${path}`);
  const bytes = readFileSync(join(dist, path));
  const text = bytes
    .toString("utf8")
    .replaceAll("http://www.w3.org/2000/svg", "")
    .replaceAll("http://www.w3.org/1999/xlink", "")
    .replaceAll("http://www.w3.org/1998/Math/MathML", "")
    .replaceAll("http://www.w3.org/1999/xhtml", "");
  if (/\.(?:html|js|css|json)$/.test(path) && /https?:\/\//i.test(text)) {
    throw new Error(`external runtime URL escaped production build: ${path}`);
  }
}

rmSync(embedded, { recursive: true, force: true });
mkdirSync(embedded, { recursive: true });
cpSync(dist, embedded, { recursive: true });

const rows = files(embedded).map((path) => {
  const contentType = new Map([
    [".css", "text/css; charset=utf-8"],
    [".html", "text/html; charset=utf-8"],
    [".js", "text/javascript; charset=utf-8"],
    [".json", "application/json; charset=utf-8"],
  ]).get(extname(path)) ?? "application/octet-stream";
  const rustPath = path.replaceAll("\\", "/");
  return `        ${JSON.stringify(rustPath)} => Some((${JSON.stringify(contentType)}, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/console/${rustPath}")))),`;
});
const source = `// @generated by console/scripts/embed-dist.mjs; do not edit by hand.\n\n#[rustfmt::skip]\npub(crate) fn get(path: &str) -> Option<(&'static str, &'static [u8])> {\n    match path {\n${rows.join("\n")}\n        _ => None,\n    }\n}\n`;
writeFileSync(generated, source, "utf8");
console.log(`embedded ${rows.length} manifest-bound console assets`);

function files(root) {
  const found = [];
  const visit = (directory) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const absolute = join(directory, entry.name);
      if (entry.isDirectory()) visit(absolute);
      else if (entry.isFile()) found.push(relative(root, absolute).replaceAll("\\", "/"));
    }
  };
  visit(root);
  return found.sort();
}
