apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hydracache.fullname" . | default "hydracache" }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hydracache
