apiVersion: v1
kind: Service
metadata:
  name: {{ include "hydracache.fullname" . | default "hydracache" }}
spec:
  selector:
    app.kubernetes.io/name: hydracache
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hydracache.fullname" . | default "hydracache" }}-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: hydracache
  ports:
    - name: cluster
      port: {{ .Values.service.clusterPort }}
      targetPort: cluster
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
