# Generated by hydracache-hc2-python-1. DO NOT EDIT.

import grpc
from . import hc2_spike_pb2 as hc2_spike__pb2

class ClientPlaneSpikeStub:
    def __init__(self, channel):
        self.Open = channel.stream_stream(
            '/hydracache.client.v2.ClientPlaneSpike/Open',
            request_serializer=hc2_spike__pb2.SpikeEnvelope.SerializeToString,
            response_deserializer=hc2_spike__pb2.SpikeEnvelope.FromString,
            _registered_method=True,
        )

class ClientPlaneSpikeServicer:
    def Open(self, request_or_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented')
        raise NotImplementedError('Method not implemented')

def add_ClientPlaneSpikeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Open': grpc.stream_stream_rpc_method_handler(
            servicer.Open,
            request_deserializer=hc2_spike__pb2.SpikeEnvelope.FromString,
            response_serializer=hc2_spike__pb2.SpikeEnvelope.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'hydracache.client.v2.ClientPlaneSpike', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydracache.client.v2.ClientPlaneSpike', rpc_method_handlers)
