# Generated by hydracache-hc2-python-1. DO NOT EDIT.

import grpc
from . import hc2_contract_pb2 as hc2_contract__pb2

class ClientPlaneAlphaStub:
    def __init__(self, channel):
        self.Open = channel.stream_stream(
            '/hydracache.client.v2alpha.ClientPlaneAlpha/Open',
            request_serializer=hc2_contract__pb2.ClientEnvelope.SerializeToString,
            response_deserializer=hc2_contract__pb2.ServerEnvelope.FromString,
            _registered_method=True,
        )

class ClientPlaneAlphaServicer:
    def Open(self, request_or_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented')
        raise NotImplementedError('Method not implemented')

def add_ClientPlaneAlphaServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Open': grpc.stream_stream_rpc_method_handler(
            servicer.Open,
            request_deserializer=hc2_contract__pb2.ClientEnvelope.FromString,
            response_serializer=hc2_contract__pb2.ServerEnvelope.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'hydracache.client.v2alpha.ClientPlaneAlpha', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydracache.client.v2alpha.ClientPlaneAlpha', rpc_method_handlers)
