# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hc2_spike.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hc2_spike.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhc2_spike.proto\x12\x14hydracache.client.v2\"Z\n\rSpikeEnvelope\x12\x12\n\ngeneration\x18\x01 \x01(\r\x12\x0c\n\x04kind\x18\x02 \x01(\r\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\x04\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x32h\n\x10\x43lientPlaneSpike\x12T\n\x04Open\x12#.hydracache.client.v2.SpikeEnvelope\x1a#.hydracache.client.v2.SpikeEnvelope(\x01\x30\x01\x42!\n\x1dio.hydracache.client.v2.spikeP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hc2_spike_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035io.hydracache.client.v2.spikeP\001'
  _globals['_SPIKEENVELOPE']._serialized_start=41
  _globals['_SPIKEENVELOPE']._serialized_end=131
  _globals['_CLIENTPLANESPIKE']._serialized_start=133
  _globals['_CLIENTPLANESPIKE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
